### ISSUE TITLE
xd

### ISSUE THREAD

**Issue by d4c5d1e0** [Implex-ltd/hcaptcha-reverse#1]
C’est vraiment bizzare cette manie chez toi de commencer un projet parler beaucoup pour rien et tout leak un mois après parce que tu te fais chier, c’est fascinant de s’en battre les couilles a ce point

**Comment by 0xF7A4C6** [comment]
je sais pas ça me prend la tête

**Comment by d4c5d1e0** [comment]
Oui fin c’est pas une raison pour à chaque fois leak et donner de la confiture aux cochons en échange de stars GitHub mdrr, c’est un comportement de gamin capricieux et impulsif. La commu discord pue la merde a cause de gens qui ont le même comportement que toi et qui leak a tout va, hCaptcha ca allait parce qu’il faut vraiment être un bouffon pour reverse hsw et penser que la meilleure des choses ça serait de le publier sur github

**Comment by 0xF7A4C6** [comment]
Ouais
