### ISSUE TITLE
how to decode octet-stream?

### ISSUE THREAD

**Issue by dr3adx** [Implex-ltd/hcaptcha-reverse#4]
From what I've seen newer chrome versions (or maybe its version unrelated and is related to hcaptcha js code) send octet-stream encoded body data while solving hcaptcha and hcaptcha replies with octet-stream body.
How can we decode the octet stream?

**Comment by zxcvqwerasdf** [comment]
It's about /getcaptcha/ request?

**Comment by dr3adx** [comment]
Yes, /getcaptcha and /checkcaptcha

**Comment by zxcvqwerasdf** [comment]
I opened hcaptcha.js in debugger, then set bp on line (15062)
```
Eo(new Uint8Array(e)).then((function(t) {
```
after some code there is 
```
then((function(t) {
                e(po.decode(t))
            }
```
and after this code
```
                "./codec-base": 9,
                "./read-core": 22,
                "./write-core": 25
            }],
            11: [function(t, e, i) {
                function n(t) {
                    if (!(this instanceof n))
                        return new n(t);
                    if (t && (this.options = t,
                    t.codec)) {
                        var e = this.codec = t.codec;
                        e.bufferish && (this.bufferish = e.bufferish)
                    }
                }
                i.DecodeBuffer = n;
                var o = t("./read-core").preset;
                t("./flex-buffer").FlexDecoder.mixin(n.prototype),
                n.prototype.codec = o,
                n.prototype.fetch = function() {
                    return this.codec.decode(this)
                }
            }
```
I didn't get what the codec is here, but after some processing you will get to
![image](https://github.com/Implex-ltd/hcaptcha-reverse/assets/67195196/1f6deda1-e73f-449d-9250-594d7926bb20)


So, how it's works:
1. parse response data as Uint8Array (byte array), then something happening (because after processing, count of bytes is decreasing), then i.ToString()
```
                i.toString = function(t, e, i) {
                    var n = this
                      , o = 0 | e;
                    i || (i = n.length);
                    for (var r = "", s = 0; o < i; )
                        (s = n[o++]) < 128 ? r += String.fromCharCode(s) : (192 == (224 & s) ? s = (31 & s) << 6 | 63 & n[o++] : 224 == (240 & s) ? s = (15 & s) << 12 | (63 & n[o++]) << 6 | 63 & n[o++] : 240 == (248 & s) && (s = (7 & s) << 18 | (63 & n[o++]) << 12 | (63 & n[o++]) << 6 | 63 & n[o++]),
                        s >= 65536 ? (s -= 65536,
                        r += String.fromCharCode(55296 + (s >>> 10), 56320 + (1023 & s))) : r += String.fromCharCode(s));
                    return r
                }
```
t is "utf-8", e is indexFrom, t is indexTo

It remains only to find out what happens between the raw http response and the call to .toString with indexes

**Comment by dr3adx** [comment]
> I opened hcaptcha.js in debugger, then set bp on line (15062)
> 
> ```
> Eo(new Uint8Array(e)).then((function(t) {
> ```
> 
> after some code there is
> 
> ```
> then((function(t) {
>                 e(po.decode(t))
>             }
> ```
> 
> and after this code
> 
> ```
>                 "./codec-base": 9,
>                 "./read-core": 22,
>                 "./write-core": 25
>             }],
>             11: [function(t, e, i) {
>                 function n(t) {
>                     if (!(this instanceof n))
>                         return new n(t);
>                     if (t && (this.options = t,
>                     t.codec)) {
>                         var e = this.codec = t.codec;
>                         e.bufferish && (this.bufferish = e.bufferish)
>                     }
>                 }
>                 i.DecodeBuffer = n;
>                 var o = t("./read-core").preset;
>                 t("./flex-buffer").FlexDecoder.mixin(n.prototype),
>                 n.prototype.codec = o,
>                 n.prototype.fetch = function() {
>                     return this.codec.decode(this)
>                 }
>             }
> ```
> 
> I didn't get what the codec is here, but after some processing you will get to ![image](https://private-user-images.githubusercontent.com/67195196/346293304-1f6deda1-e73f-449d-9250-594d7926bb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTUzNDksIm5iZiI6MTcyMDI5NTA0OSwicGF0aCI6Ii82NzE5NTE5Ni8zNDYyOTMzMDQtMWY2ZGVkYTEtZTczZi00NDlkLTkyNTAtNTk0ZDc5MjZiYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE5NDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNGZlMDBjYmEyODk1Y2JlNjMwNGE2Y2ZhOTg2NWRkZjk1ZmYzYWVlMTgzYjkyNmFjM2E5NzI3N2FjYmZlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YiG9_Ht5m2xYia-Kcd97PTDMs1AX9PB-68jkEJSaLUA)
> 
> So, how it's works:
> 
> 1. parse response data as Uint8Array (byte array), then something happening (because after processing, count of bytes is decreasing), then i.ToString()
> 
> ```
>                 i.toString = function(t, e, i) {
>                     var n = this
>                       , o = 0 | e;
>                     i || (i = n.length);
>                     for (var r = "", s = 0; o < i; )
>                         (s = n[o++]) < 128 ? r += String.fromCharCode(s) : (192 == (224 & s) ? s = (31 & s) << 6 | 63 & n[o++] : 224 == (240 & s) ? s = (15 & s) << 12 | (63 & n[o++]) << 6 | 63 & n[o++] : 240 == (248 & s) && (s = (7 & s) << 18 | (63 & n[o++]) << 12 | (63 & n[o++]) << 6 | 63 & n[o++]),
>                         s >= 65536 ? (s -= 65536,
>                         r += String.fromCharCode(55296 + (s >>> 10), 56320 + (1023 & s))) : r += String.fromCharCode(s));
>                     return r
>                 }
> ```
> 
> t is "utf-8", e is indexFrom, t is indexTo
> 
> It remains only to find out what happens between the raw http response and the call to .toString with indexes

yeah i came to some findings since the time i posted this, do u have discord or telegram so we can discuss this further?

**Comment by zxcvqwerasdf** [comment]
Change Accept header to application/json

**Comment by dr3adx** [comment]
> Change Accept header to application/json

thats not the solution its very easily detected, because browser that supports arraybuffer will never request json response, give me  your discord/telegram so we can talk properly

**Comment by zxcvqwerasdf** [comment]
> > Change Accept header to application/json
> 
> thats not the solution its very easily detected, because browser that supports arraybuffer will never request json response, give me your discord/telegram so we can talk properly

It's working for now. Also after any error hcaptcha start requesting json instead of octet without any problem. I think it's because of backward compatibility, sended friend request in discord to dr3adx username.

**Comment by dr3adx** [comment]
> > > Change Accept header to application/json
> > 
> > 
> > thats not the solution its very easily detected, because browser that supports arraybuffer will never request json response, give me your discord/telegram so we can talk properly
> 
> It's working for now. Also after any error hcaptcha start requesting json instead of octet without any problem. I think it's because of backward compatibility, sended friend request in discord to dr3adx username.

this is my discord: --

**Comment by kekeds** [comment]
dm https://t.me/kokandg if you want to buy whole reverse for the request encryption!!

**Comment by yk303** [comment]
> Author

did you find solution for that?
